### ISSUE TITLE
Pull new incremental patches on Drupal.org from this repository

### ISSUE THREAD

**Issue by mortenson** [bforchhammer/geocoder#5]
It would be helpful if patches were pulled every week/few weeks and posted to the Drupal 8 porting issue (https://www.drupal.org/node/2146393). People (including myself) have been working on new patches based on that issue, but most of the work has already been done in this repository.

A timeline on deprecating this repository and using Drupal.org would help as well.

**Comment by webflo** [comment]
Please use the 2.x branch from Drupal.org instead. Thanks! See you there.
