### ISSUE TITLE
Let's work together

### ISSUE THREAD

**Issue by drupol** [bforchhammer/geocoder#7]
Hi,

I made a new release of Geocoder 2.x for Drupal 7 and 8 and I'm sending you this message to know if you would like to work on it.
It's based on Geocoder PHP and you can extend the Providers AND the Dumpers within Drupal directly.
The code from the D7 version is 90% the same as the code from 8.x (It's based on Service Container).

Have a look at the readme: https://github.com/drupol/geocoder/tree/8.x-2.x

Let me know what you think!

**Comment by webflo** [comment]
Thanks, the 2.x version looks good. I have added a deprecation notice to this repo.
